// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAlw8pY9BmPAFwc_yK08JJsTFz_JxT9EeU',
    appId: '1:773161109315:web:99e4f9dffe79cf788591f6',
    messagingSenderId: '773161109315',
    projectId: 'matchplanner-33a1e',
    authDomain: 'matchplanner-33a1e.firebaseapp.com',
    storageBucket: 'matchplanner-33a1e.appspot.com',
    measurementId: 'G-4SXZGPNFXV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDIyXlMWk9WpbLWCvsGuEEdIzpvWhepxvM',
    appId: '1:773161109315:android:1cec4db01b6f74c58591f6',
    messagingSenderId: '773161109315',
    projectId: 'matchplanner-33a1e',
    storageBucket: 'matchplanner-33a1e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD2uL98nhjTIJvP0LJBLfT5k7FuMgUNclQ',
    appId: '1:773161109315:ios:2c1991a05c28fe2b8591f6',
    messagingSenderId: '773161109315',
    projectId: 'matchplanner-33a1e',
    storageBucket: 'matchplanner-33a1e.appspot.com',
    iosBundleId: 'com.example.matchesTable',
  );
}
